// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetDBaaSLogsInputEngine
    {
        /// <summary>
        /// Use this data source to retrieve information about a DBaas logs input engine.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var logstash = Output.Create(Ovh.GetDBaaSLogsInputEngine.InvokeAsync(new Ovh.GetDBaaSLogsInputEngineArgs
        ///         {
        ///             IsDeprecated = true,
        ///             Name = "logstash",
        ///             Version = "6.8",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDBaaSLogsInputEngineResult> InvokeAsync(GetDBaaSLogsInputEngineArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDBaaSLogsInputEngineResult>("ovh:index/getDBaaSLogsInputEngine:getDBaaSLogsInputEngine", args ?? new GetDBaaSLogsInputEngineArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about a DBaas logs input engine.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var logstash = Output.Create(Ovh.GetDBaaSLogsInputEngine.InvokeAsync(new Ovh.GetDBaaSLogsInputEngineArgs
        ///         {
        ///             IsDeprecated = true,
        ///             Name = "logstash",
        ///             Version = "6.8",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetDBaaSLogsInputEngineResult> Invoke(GetDBaaSLogsInputEngineInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetDBaaSLogsInputEngineResult>("ovh:index/getDBaaSLogsInputEngine:getDBaaSLogsInputEngine", args ?? new GetDBaaSLogsInputEngineInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDBaaSLogsInputEngineArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Indicates if engine will soon not be supported.
        /// </summary>
        [Input("isDeprecated")]
        public bool? IsDeprecated { get; set; }

        /// <summary>
        /// The name of the logs input engine.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Software version
        /// </summary>
        [Input("version")]
        public string? Version { get; set; }

        public GetDBaaSLogsInputEngineArgs()
        {
        }
    }

    public sealed class GetDBaaSLogsInputEngineInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Indicates if engine will soon not be supported.
        /// </summary>
        [Input("isDeprecated")]
        public Input<bool>? IsDeprecated { get; set; }

        /// <summary>
        /// The name of the logs input engine.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Software version
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public GetDBaaSLogsInputEngineInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDBaaSLogsInputEngineResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsDeprecated;
        public readonly string Name;
        public readonly string Version;

        [OutputConstructor]
        private GetDBaaSLogsInputEngineResult(
            string id,

            bool isDeprecated,

            string name,

            string version)
        {
            Id = id;
            IsDeprecated = isDeprecated;
            Name = name;
            Version = version;
        }
    }
}
