// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    public static class GetIPLoadBalancingVRackNetworks
    {
        /// <summary>
        /// Use this data source to get the list of Vrack network ids available for your IPLoadbalancer associated with your OVH account.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var lbNetworks = Output.Create(Ovh.GetIPLoadBalancingVRackNetworks.InvokeAsync(new Ovh.GetIPLoadBalancingVRackNetworksArgs
        ///         {
        ///             ServiceName = "XXXXXX",
        ///             Subnet = "10.0.0.0/24",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetIPLoadBalancingVRackNetworksResult> InvokeAsync(GetIPLoadBalancingVRackNetworksArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetIPLoadBalancingVRackNetworksResult>("ovh:index/getIPLoadBalancingVRackNetworks:getIPLoadBalancingVRackNetworks", args ?? new GetIPLoadBalancingVRackNetworksArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get the list of Vrack network ids available for your IPLoadbalancer associated with your OVH account.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var lbNetworks = Output.Create(Ovh.GetIPLoadBalancingVRackNetworks.InvokeAsync(new Ovh.GetIPLoadBalancingVRackNetworksArgs
        ///         {
        ///             ServiceName = "XXXXXX",
        ///             Subnet = "10.0.0.0/24",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetIPLoadBalancingVRackNetworksResult> Invoke(GetIPLoadBalancingVRackNetworksInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetIPLoadBalancingVRackNetworksResult>("ovh:index/getIPLoadBalancingVRackNetworks:getIPLoadBalancingVRackNetworks", args ?? new GetIPLoadBalancingVRackNetworksInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIPLoadBalancingVRackNetworksArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The internal name of your IP load balancing
        /// </summary>
        [Input("serviceName", required: true)]
        public string ServiceName { get; set; } = null!;

        /// <summary>
        /// Filters networks on the subnet.
        /// </summary>
        [Input("subnet")]
        public string? Subnet { get; set; }

        /// <summary>
        /// Filters networks on the vlan id.
        /// </summary>
        [Input("vlanId")]
        public int? VlanId { get; set; }

        public GetIPLoadBalancingVRackNetworksArgs()
        {
        }
    }

    public sealed class GetIPLoadBalancingVRackNetworksInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The internal name of your IP load balancing
        /// </summary>
        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        /// <summary>
        /// Filters networks on the subnet.
        /// </summary>
        [Input("subnet")]
        public Input<string>? Subnet { get; set; }

        /// <summary>
        /// Filters networks on the vlan id.
        /// </summary>
        [Input("vlanId")]
        public Input<int>? VlanId { get; set; }

        public GetIPLoadBalancingVRackNetworksInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetIPLoadBalancingVRackNetworksResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of vrack network ids.
        /// </summary>
        public readonly ImmutableArray<int> Results;
        public readonly string ServiceName;
        public readonly string? Subnet;
        public readonly int? VlanId;

        [OutputConstructor]
        private GetIPLoadBalancingVRackNetworksResult(
            string id,

            ImmutableArray<int> results,

            string serviceName,

            string? subnet,

            int? vlanId)
        {
            Id = id;
            Results = results;
            ServiceName = serviceName;
            Subnet = subnet;
            VlanId = vlanId;
        }
    }
}
