// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    /// <summary>
    /// Orders an ip service.
    /// 
    /// ## Important
    /// 
    /// This resource orders an OVH product for a long period of time and may generate heavy costs !
    /// Use with caution.
    /// 
    /// __NOTE__ 1: the "default-payment-mean" will scan your registered bank accounts, credit card and paypal payment means to find your default payment mean.
    /// 
    /// __NOTE__ 2: this resource is in beta state. Use with caution.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Ovh = Pulumi.Ovh;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var mycart = Output.Create(Ovh.GetOrderCart.InvokeAsync(new Ovh.GetOrderCartArgs
    ///         {
    ///             OvhSubsidiary = "fr",
    ///             Description = "order ip block",
    ///         }));
    ///         var ipblockProductCartProductPlan = mycart.Apply(mycart =&gt; Output.Create(Ovh.GetProductCartProductPlan.InvokeAsync(new Ovh.GetProductCartProductPlanArgs
    ///         {
    ///             CartId = mycart.Id,
    ///             PriceCapacity = "renew",
    ///             Product = "ip",
    ///             PlanCode = "ip-v4-s30-ripe",
    ///         })));
    ///         var ipblockIPService = new Ovh.IPService("ipblockIPService", new Ovh.IPServiceArgs
    ///         {
    ///             OvhSubsidiary = mycart.Apply(mycart =&gt; mycart.OvhSubsidiary),
    ///             PaymentMean = "ovh-account",
    ///             Description = "my ip block",
    ///             Plan = new Ovh.Inputs.IPServicePlanArgs
    ///             {
    ///                 Duration = ipblockProductCartProductPlan.Apply(ipblockProductCartProductPlan =&gt; ipblockProductCartProductPlan.SelectedPrices?[0]?.Duration),
    ///                 PlanCode = ipblockProductCartProductPlan.Apply(ipblockProductCartProductPlan =&gt; ipblockProductCartProductPlan.PlanCode),
    ///                 PricingMode = ipblockProductCartProductPlan.Apply(ipblockProductCartProductPlan =&gt; ipblockProductCartProductPlan.SelectedPrices?[0]?.PricingMode),
    ///                 Configurations = 
    ///                 {
    ///                     new Ovh.Inputs.IPServicePlanConfigurationArgs
    ///                     {
    ///                         Label = "country",
    ///                         Value = "FR",
    ///                     },
    ///                 },
    ///             },
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [OvhResourceType("ovh:index/iPService:IPService")]
    public partial class IPService : Pulumi.CustomResource
    {
        /// <summary>
        /// can be terminated
        /// </summary>
        [Output("canBeTerminated")]
        public Output<bool> CanBeTerminated { get; private set; } = null!;

        /// <summary>
        /// country
        /// </summary>
        [Output("country")]
        public Output<string> Country { get; private set; } = null!;

        /// <summary>
        /// Custom description on your ip.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// ip block
        /// </summary>
        [Output("ip")]
        public Output<string> Ip { get; private set; } = null!;

        /// <summary>
        /// Details about an Order
        /// </summary>
        [Output("orders")]
        public Output<ImmutableArray<Outputs.IPServiceOrder>> Orders { get; private set; } = null!;

        /// <summary>
        /// IP block organisation Id
        /// </summary>
        [Output("organisationId")]
        public Output<string> OrganisationId { get; private set; } = null!;

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Output("ovhSubsidiary")]
        public Output<string> OvhSubsidiary { get; private set; } = null!;

        /// <summary>
        /// Ovh payment mode (One of "default-payment-mean", "fidelity", "ovh-account")
        /// </summary>
        [Output("paymentMean")]
        public Output<string> PaymentMean { get; private set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Output("plan")]
        public Output<Outputs.IPServicePlan> Plan { get; private set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Output("planOptions")]
        public Output<ImmutableArray<Outputs.IPServicePlanOption>> PlanOptions { get; private set; } = null!;

        /// <summary>
        /// Routage information
        /// </summary>
        [Output("routedTos")]
        public Output<ImmutableArray<Outputs.IPServiceRoutedTo>> RoutedTos { get; private set; } = null!;

        /// <summary>
        /// Service where ip is routed to
        /// * `service_name`: service name
        /// </summary>
        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        /// <summary>
        /// Possible values for ip type
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a IPService resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IPService(string name, IPServiceArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/iPService:IPService", name, args ?? new IPServiceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IPService(string name, Input<string> id, IPServiceState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/iPService:IPService", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IPService resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IPService Get(string name, Input<string> id, IPServiceState? state = null, CustomResourceOptions? options = null)
        {
            return new IPService(name, id, state, options);
        }
    }

    public sealed class IPServiceArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Custom description on your ip.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Input("ovhSubsidiary", required: true)]
        public Input<string> OvhSubsidiary { get; set; } = null!;

        /// <summary>
        /// Ovh payment mode (One of "default-payment-mean", "fidelity", "ovh-account")
        /// </summary>
        [Input("paymentMean", required: true)]
        public Input<string> PaymentMean { get; set; } = null!;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Input("plan", required: true)]
        public Input<Inputs.IPServicePlanArgs> Plan { get; set; } = null!;

        [Input("planOptions")]
        private InputList<Inputs.IPServicePlanOptionArgs>? _planOptions;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        public InputList<Inputs.IPServicePlanOptionArgs> PlanOptions
        {
            get => _planOptions ?? (_planOptions = new InputList<Inputs.IPServicePlanOptionArgs>());
            set => _planOptions = value;
        }

        public IPServiceArgs()
        {
        }
    }

    public sealed class IPServiceState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// can be terminated
        /// </summary>
        [Input("canBeTerminated")]
        public Input<bool>? CanBeTerminated { get; set; }

        /// <summary>
        /// country
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        /// <summary>
        /// Custom description on your ip.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// ip block
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("orders")]
        private InputList<Inputs.IPServiceOrderGetArgs>? _orders;

        /// <summary>
        /// Details about an Order
        /// </summary>
        public InputList<Inputs.IPServiceOrderGetArgs> Orders
        {
            get => _orders ?? (_orders = new InputList<Inputs.IPServiceOrderGetArgs>());
            set => _orders = value;
        }

        /// <summary>
        /// IP block organisation Id
        /// </summary>
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        /// <summary>
        /// Ovh Subsidiary
        /// </summary>
        [Input("ovhSubsidiary")]
        public Input<string>? OvhSubsidiary { get; set; }

        /// <summary>
        /// Ovh payment mode (One of "default-payment-mean", "fidelity", "ovh-account")
        /// </summary>
        [Input("paymentMean")]
        public Input<string>? PaymentMean { get; set; }

        /// <summary>
        /// Product Plan to order
        /// </summary>
        [Input("plan")]
        public Input<Inputs.IPServicePlanGetArgs>? Plan { get; set; }

        [Input("planOptions")]
        private InputList<Inputs.IPServicePlanOptionGetArgs>? _planOptions;

        /// <summary>
        /// Product Plan to order
        /// </summary>
        public InputList<Inputs.IPServicePlanOptionGetArgs> PlanOptions
        {
            get => _planOptions ?? (_planOptions = new InputList<Inputs.IPServicePlanOptionGetArgs>());
            set => _planOptions = value;
        }

        [Input("routedTos")]
        private InputList<Inputs.IPServiceRoutedToGetArgs>? _routedTos;

        /// <summary>
        /// Routage information
        /// </summary>
        public InputList<Inputs.IPServiceRoutedToGetArgs> RoutedTos
        {
            get => _routedTos ?? (_routedTos = new InputList<Inputs.IPServiceRoutedToGetArgs>());
            set => _routedTos = value;
        }

        /// <summary>
        /// Service where ip is routed to
        /// * `service_name`: service name
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        /// <summary>
        /// Possible values for ip type
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public IPServiceState()
        {
        }
    }
}
