// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    /// <summary>
    /// Attach a dedicated server to a VRack.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Ovh = Pulumi.Ovh;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var vds = new Ovh.VRackDedicatedServer("vds", new Ovh.VRackDedicatedServerArgs
    ///         {
    ///             ServerId = "67890",
    ///             ServiceName = "XXXX",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// </summary>
    [OvhResourceType("ovh:index/vRackDedicatedServer:VRackDedicatedServer")]
    public partial class VRackDedicatedServer : Pulumi.CustomResource
    {
        /// <summary>
        /// The id of the dedicated server.
        /// </summary>
        [Output("serverId")]
        public Output<string> ServerId { get; private set; } = null!;

        /// <summary>
        /// The id of the vrack. If omitted,
        /// the `OVH_VRACK_SERVICE` environment variable is used.
        /// </summary>
        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;


        /// <summary>
        /// Create a VRackDedicatedServer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VRackDedicatedServer(string name, VRackDedicatedServerArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/vRackDedicatedServer:VRackDedicatedServer", name, args ?? new VRackDedicatedServerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VRackDedicatedServer(string name, Input<string> id, VRackDedicatedServerState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/vRackDedicatedServer:VRackDedicatedServer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VRackDedicatedServer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VRackDedicatedServer Get(string name, Input<string> id, VRackDedicatedServerState? state = null, CustomResourceOptions? options = null)
        {
            return new VRackDedicatedServer(name, id, state, options);
        }
    }

    public sealed class VRackDedicatedServerArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The id of the dedicated server.
        /// </summary>
        [Input("serverId", required: true)]
        public Input<string> ServerId { get; set; } = null!;

        /// <summary>
        /// The id of the vrack. If omitted,
        /// the `OVH_VRACK_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        public VRackDedicatedServerArgs()
        {
        }
    }

    public sealed class VRackDedicatedServerState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The id of the dedicated server.
        /// </summary>
        [Input("serverId")]
        public Input<string>? ServerId { get; set; }

        /// <summary>
        /// The id of the vrack. If omitted,
        /// the `OVH_VRACK_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        public VRackDedicatedServerState()
        {
        }
    }
}
