// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DBaaSLogsOutputGraylogStream struct {
	pulumi.CustomResourceState

	// Indicates if the current user can create alert on the stream
	CanAlert pulumi.BoolOutput `pulumi:"canAlert"`
	// Cold storage compression method
	ColdStorageCompression pulumi.StringOutput `pulumi:"coldStorageCompression"`
	// ColdStorage content
	ColdStorageContent pulumi.StringOutput `pulumi:"coldStorageContent"`
	// Is Cold storage enabled?
	ColdStorageEnabled pulumi.BoolOutput `pulumi:"coldStorageEnabled"`
	// Notify on new Cold storage archive
	ColdStorageNotifyEnabled pulumi.BoolOutput `pulumi:"coldStorageNotifyEnabled"`
	// Cold storage retention in year
	ColdStorageRetention pulumi.IntOutput `pulumi:"coldStorageRetention"`
	// ColdStorage destination
	ColdStorageTarget pulumi.StringOutput `pulumi:"coldStorageTarget"`
	// Stream creation
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Stream description
	Description pulumi.StringOutput `pulumi:"description"`
	// Enable ES indexing
	IndexingEnabled pulumi.BoolOutput `pulumi:"indexingEnabled"`
	// Maximum indexing size (in GB)
	IndexingMaxSize pulumi.IntOutput `pulumi:"indexingMaxSize"`
	// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
	IndexingNotifyEnabled pulumi.BoolOutput `pulumi:"indexingNotifyEnabled"`
	// Indicates if you are allowed to edit entry
	IsEditable pulumi.BoolOutput `pulumi:"isEditable"`
	// Indicates if you are allowed to share entry
	IsShareable pulumi.BoolOutput `pulumi:"isShareable"`
	// Number of alert condition
	NbAlertCondition pulumi.IntOutput `pulumi:"nbAlertCondition"`
	// Number of coldstored archives
	NbArchive pulumi.IntOutput `pulumi:"nbArchive"`
	// Parent stream ID
	ParentStreamId pulumi.StringPtrOutput `pulumi:"parentStreamId"`
	// If set, pause indexing when maximum size is reach
	PauseIndexingOnMaxSize pulumi.BoolOutput `pulumi:"pauseIndexingOnMaxSize"`
	// Retention ID
	RetentionId pulumi.StringOutput `pulumi:"retentionId"`
	// The service name
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
	// Stream ID
	StreamId pulumi.StringOutput `pulumi:"streamId"`
	// Stream description
	Title pulumi.StringOutput `pulumi:"title"`
	// Stream last update
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// Enable Websocket
	WebSocketEnabled pulumi.BoolOutput `pulumi:"webSocketEnabled"`
}

// NewDBaaSLogsOutputGraylogStream registers a new resource with the given unique name, arguments, and options.
func NewDBaaSLogsOutputGraylogStream(ctx *pulumi.Context,
	name string, args *DBaaSLogsOutputGraylogStreamArgs, opts ...pulumi.ResourceOption) (*DBaaSLogsOutputGraylogStream, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	if args.Title == nil {
		return nil, errors.New("invalid value for required argument 'Title'")
	}
	var resource DBaaSLogsOutputGraylogStream
	err := ctx.RegisterResource("ovh:index/dBaaSLogsOutputGraylogStream:DBaaSLogsOutputGraylogStream", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDBaaSLogsOutputGraylogStream gets an existing DBaaSLogsOutputGraylogStream resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDBaaSLogsOutputGraylogStream(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DBaaSLogsOutputGraylogStreamState, opts ...pulumi.ResourceOption) (*DBaaSLogsOutputGraylogStream, error) {
	var resource DBaaSLogsOutputGraylogStream
	err := ctx.ReadResource("ovh:index/dBaaSLogsOutputGraylogStream:DBaaSLogsOutputGraylogStream", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DBaaSLogsOutputGraylogStream resources.
type dbaaSLogsOutputGraylogStreamState struct {
	// Indicates if the current user can create alert on the stream
	CanAlert *bool `pulumi:"canAlert"`
	// Cold storage compression method
	ColdStorageCompression *string `pulumi:"coldStorageCompression"`
	// ColdStorage content
	ColdStorageContent *string `pulumi:"coldStorageContent"`
	// Is Cold storage enabled?
	ColdStorageEnabled *bool `pulumi:"coldStorageEnabled"`
	// Notify on new Cold storage archive
	ColdStorageNotifyEnabled *bool `pulumi:"coldStorageNotifyEnabled"`
	// Cold storage retention in year
	ColdStorageRetention *int `pulumi:"coldStorageRetention"`
	// ColdStorage destination
	ColdStorageTarget *string `pulumi:"coldStorageTarget"`
	// Stream creation
	CreatedAt *string `pulumi:"createdAt"`
	// Stream description
	Description *string `pulumi:"description"`
	// Enable ES indexing
	IndexingEnabled *bool `pulumi:"indexingEnabled"`
	// Maximum indexing size (in GB)
	IndexingMaxSize *int `pulumi:"indexingMaxSize"`
	// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
	IndexingNotifyEnabled *bool `pulumi:"indexingNotifyEnabled"`
	// Indicates if you are allowed to edit entry
	IsEditable *bool `pulumi:"isEditable"`
	// Indicates if you are allowed to share entry
	IsShareable *bool `pulumi:"isShareable"`
	// Number of alert condition
	NbAlertCondition *int `pulumi:"nbAlertCondition"`
	// Number of coldstored archives
	NbArchive *int `pulumi:"nbArchive"`
	// Parent stream ID
	ParentStreamId *string `pulumi:"parentStreamId"`
	// If set, pause indexing when maximum size is reach
	PauseIndexingOnMaxSize *bool `pulumi:"pauseIndexingOnMaxSize"`
	// Retention ID
	RetentionId *string `pulumi:"retentionId"`
	// The service name
	ServiceName *string `pulumi:"serviceName"`
	// Stream ID
	StreamId *string `pulumi:"streamId"`
	// Stream description
	Title *string `pulumi:"title"`
	// Stream last update
	UpdatedAt *string `pulumi:"updatedAt"`
	// Enable Websocket
	WebSocketEnabled *bool `pulumi:"webSocketEnabled"`
}

type DBaaSLogsOutputGraylogStreamState struct {
	// Indicates if the current user can create alert on the stream
	CanAlert pulumi.BoolPtrInput
	// Cold storage compression method
	ColdStorageCompression pulumi.StringPtrInput
	// ColdStorage content
	ColdStorageContent pulumi.StringPtrInput
	// Is Cold storage enabled?
	ColdStorageEnabled pulumi.BoolPtrInput
	// Notify on new Cold storage archive
	ColdStorageNotifyEnabled pulumi.BoolPtrInput
	// Cold storage retention in year
	ColdStorageRetention pulumi.IntPtrInput
	// ColdStorage destination
	ColdStorageTarget pulumi.StringPtrInput
	// Stream creation
	CreatedAt pulumi.StringPtrInput
	// Stream description
	Description pulumi.StringPtrInput
	// Enable ES indexing
	IndexingEnabled pulumi.BoolPtrInput
	// Maximum indexing size (in GB)
	IndexingMaxSize pulumi.IntPtrInput
	// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
	IndexingNotifyEnabled pulumi.BoolPtrInput
	// Indicates if you are allowed to edit entry
	IsEditable pulumi.BoolPtrInput
	// Indicates if you are allowed to share entry
	IsShareable pulumi.BoolPtrInput
	// Number of alert condition
	NbAlertCondition pulumi.IntPtrInput
	// Number of coldstored archives
	NbArchive pulumi.IntPtrInput
	// Parent stream ID
	ParentStreamId pulumi.StringPtrInput
	// If set, pause indexing when maximum size is reach
	PauseIndexingOnMaxSize pulumi.BoolPtrInput
	// Retention ID
	RetentionId pulumi.StringPtrInput
	// The service name
	ServiceName pulumi.StringPtrInput
	// Stream ID
	StreamId pulumi.StringPtrInput
	// Stream description
	Title pulumi.StringPtrInput
	// Stream last update
	UpdatedAt pulumi.StringPtrInput
	// Enable Websocket
	WebSocketEnabled pulumi.BoolPtrInput
}

func (DBaaSLogsOutputGraylogStreamState) ElementType() reflect.Type {
	return reflect.TypeOf((*dbaaSLogsOutputGraylogStreamState)(nil)).Elem()
}

type dbaaSLogsOutputGraylogStreamArgs struct {
	// Cold storage compression method
	ColdStorageCompression *string `pulumi:"coldStorageCompression"`
	// ColdStorage content
	ColdStorageContent *string `pulumi:"coldStorageContent"`
	// Is Cold storage enabled?
	ColdStorageEnabled *bool `pulumi:"coldStorageEnabled"`
	// Notify on new Cold storage archive
	ColdStorageNotifyEnabled *bool `pulumi:"coldStorageNotifyEnabled"`
	// Cold storage retention in year
	ColdStorageRetention *int `pulumi:"coldStorageRetention"`
	// ColdStorage destination
	ColdStorageTarget *string `pulumi:"coldStorageTarget"`
	// Stream description
	Description string `pulumi:"description"`
	// Enable ES indexing
	IndexingEnabled *bool `pulumi:"indexingEnabled"`
	// Maximum indexing size (in GB)
	IndexingMaxSize *int `pulumi:"indexingMaxSize"`
	// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
	IndexingNotifyEnabled *bool `pulumi:"indexingNotifyEnabled"`
	// Parent stream ID
	ParentStreamId *string `pulumi:"parentStreamId"`
	// If set, pause indexing when maximum size is reach
	PauseIndexingOnMaxSize *bool `pulumi:"pauseIndexingOnMaxSize"`
	// Retention ID
	RetentionId *string `pulumi:"retentionId"`
	// The service name
	ServiceName string `pulumi:"serviceName"`
	// Stream description
	Title string `pulumi:"title"`
	// Enable Websocket
	WebSocketEnabled *bool `pulumi:"webSocketEnabled"`
}

// The set of arguments for constructing a DBaaSLogsOutputGraylogStream resource.
type DBaaSLogsOutputGraylogStreamArgs struct {
	// Cold storage compression method
	ColdStorageCompression pulumi.StringPtrInput
	// ColdStorage content
	ColdStorageContent pulumi.StringPtrInput
	// Is Cold storage enabled?
	ColdStorageEnabled pulumi.BoolPtrInput
	// Notify on new Cold storage archive
	ColdStorageNotifyEnabled pulumi.BoolPtrInput
	// Cold storage retention in year
	ColdStorageRetention pulumi.IntPtrInput
	// ColdStorage destination
	ColdStorageTarget pulumi.StringPtrInput
	// Stream description
	Description pulumi.StringInput
	// Enable ES indexing
	IndexingEnabled pulumi.BoolPtrInput
	// Maximum indexing size (in GB)
	IndexingMaxSize pulumi.IntPtrInput
	// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
	IndexingNotifyEnabled pulumi.BoolPtrInput
	// Parent stream ID
	ParentStreamId pulumi.StringPtrInput
	// If set, pause indexing when maximum size is reach
	PauseIndexingOnMaxSize pulumi.BoolPtrInput
	// Retention ID
	RetentionId pulumi.StringPtrInput
	// The service name
	ServiceName pulumi.StringInput
	// Stream description
	Title pulumi.StringInput
	// Enable Websocket
	WebSocketEnabled pulumi.BoolPtrInput
}

func (DBaaSLogsOutputGraylogStreamArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dbaaSLogsOutputGraylogStreamArgs)(nil)).Elem()
}

type DBaaSLogsOutputGraylogStreamInput interface {
	pulumi.Input

	ToDBaaSLogsOutputGraylogStreamOutput() DBaaSLogsOutputGraylogStreamOutput
	ToDBaaSLogsOutputGraylogStreamOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamOutput
}

func (*DBaaSLogsOutputGraylogStream) ElementType() reflect.Type {
	return reflect.TypeOf((**DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (i *DBaaSLogsOutputGraylogStream) ToDBaaSLogsOutputGraylogStreamOutput() DBaaSLogsOutputGraylogStreamOutput {
	return i.ToDBaaSLogsOutputGraylogStreamOutputWithContext(context.Background())
}

func (i *DBaaSLogsOutputGraylogStream) ToDBaaSLogsOutputGraylogStreamOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DBaaSLogsOutputGraylogStreamOutput)
}

// DBaaSLogsOutputGraylogStreamArrayInput is an input type that accepts DBaaSLogsOutputGraylogStreamArray and DBaaSLogsOutputGraylogStreamArrayOutput values.
// You can construct a concrete instance of `DBaaSLogsOutputGraylogStreamArrayInput` via:
//
//          DBaaSLogsOutputGraylogStreamArray{ DBaaSLogsOutputGraylogStreamArgs{...} }
type DBaaSLogsOutputGraylogStreamArrayInput interface {
	pulumi.Input

	ToDBaaSLogsOutputGraylogStreamArrayOutput() DBaaSLogsOutputGraylogStreamArrayOutput
	ToDBaaSLogsOutputGraylogStreamArrayOutputWithContext(context.Context) DBaaSLogsOutputGraylogStreamArrayOutput
}

type DBaaSLogsOutputGraylogStreamArray []DBaaSLogsOutputGraylogStreamInput

func (DBaaSLogsOutputGraylogStreamArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (i DBaaSLogsOutputGraylogStreamArray) ToDBaaSLogsOutputGraylogStreamArrayOutput() DBaaSLogsOutputGraylogStreamArrayOutput {
	return i.ToDBaaSLogsOutputGraylogStreamArrayOutputWithContext(context.Background())
}

func (i DBaaSLogsOutputGraylogStreamArray) ToDBaaSLogsOutputGraylogStreamArrayOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DBaaSLogsOutputGraylogStreamArrayOutput)
}

// DBaaSLogsOutputGraylogStreamMapInput is an input type that accepts DBaaSLogsOutputGraylogStreamMap and DBaaSLogsOutputGraylogStreamMapOutput values.
// You can construct a concrete instance of `DBaaSLogsOutputGraylogStreamMapInput` via:
//
//          DBaaSLogsOutputGraylogStreamMap{ "key": DBaaSLogsOutputGraylogStreamArgs{...} }
type DBaaSLogsOutputGraylogStreamMapInput interface {
	pulumi.Input

	ToDBaaSLogsOutputGraylogStreamMapOutput() DBaaSLogsOutputGraylogStreamMapOutput
	ToDBaaSLogsOutputGraylogStreamMapOutputWithContext(context.Context) DBaaSLogsOutputGraylogStreamMapOutput
}

type DBaaSLogsOutputGraylogStreamMap map[string]DBaaSLogsOutputGraylogStreamInput

func (DBaaSLogsOutputGraylogStreamMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (i DBaaSLogsOutputGraylogStreamMap) ToDBaaSLogsOutputGraylogStreamMapOutput() DBaaSLogsOutputGraylogStreamMapOutput {
	return i.ToDBaaSLogsOutputGraylogStreamMapOutputWithContext(context.Background())
}

func (i DBaaSLogsOutputGraylogStreamMap) ToDBaaSLogsOutputGraylogStreamMapOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DBaaSLogsOutputGraylogStreamMapOutput)
}

type DBaaSLogsOutputGraylogStreamOutput struct{ *pulumi.OutputState }

func (DBaaSLogsOutputGraylogStreamOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (o DBaaSLogsOutputGraylogStreamOutput) ToDBaaSLogsOutputGraylogStreamOutput() DBaaSLogsOutputGraylogStreamOutput {
	return o
}

func (o DBaaSLogsOutputGraylogStreamOutput) ToDBaaSLogsOutputGraylogStreamOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamOutput {
	return o
}

// Indicates if the current user can create alert on the stream
func (o DBaaSLogsOutputGraylogStreamOutput) CanAlert() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.CanAlert }).(pulumi.BoolOutput)
}

// Cold storage compression method
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageCompression() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.ColdStorageCompression }).(pulumi.StringOutput)
}

// ColdStorage content
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageContent() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.ColdStorageContent }).(pulumi.StringOutput)
}

// Is Cold storage enabled?
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.ColdStorageEnabled }).(pulumi.BoolOutput)
}

// Notify on new Cold storage archive
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageNotifyEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.ColdStorageNotifyEnabled }).(pulumi.BoolOutput)
}

// Cold storage retention in year
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageRetention() pulumi.IntOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.IntOutput { return v.ColdStorageRetention }).(pulumi.IntOutput)
}

// ColdStorage destination
func (o DBaaSLogsOutputGraylogStreamOutput) ColdStorageTarget() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.ColdStorageTarget }).(pulumi.StringOutput)
}

// Stream creation
func (o DBaaSLogsOutputGraylogStreamOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Stream description
func (o DBaaSLogsOutputGraylogStreamOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Enable ES indexing
func (o DBaaSLogsOutputGraylogStreamOutput) IndexingEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.IndexingEnabled }).(pulumi.BoolOutput)
}

// Maximum indexing size (in GB)
func (o DBaaSLogsOutputGraylogStreamOutput) IndexingMaxSize() pulumi.IntOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.IntOutput { return v.IndexingMaxSize }).(pulumi.IntOutput)
}

// If set, notify when size is near 80, 90 or 100 % of the maximum configured setting
func (o DBaaSLogsOutputGraylogStreamOutput) IndexingNotifyEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.IndexingNotifyEnabled }).(pulumi.BoolOutput)
}

// Indicates if you are allowed to edit entry
func (o DBaaSLogsOutputGraylogStreamOutput) IsEditable() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.IsEditable }).(pulumi.BoolOutput)
}

// Indicates if you are allowed to share entry
func (o DBaaSLogsOutputGraylogStreamOutput) IsShareable() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.IsShareable }).(pulumi.BoolOutput)
}

// Number of alert condition
func (o DBaaSLogsOutputGraylogStreamOutput) NbAlertCondition() pulumi.IntOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.IntOutput { return v.NbAlertCondition }).(pulumi.IntOutput)
}

// Number of coldstored archives
func (o DBaaSLogsOutputGraylogStreamOutput) NbArchive() pulumi.IntOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.IntOutput { return v.NbArchive }).(pulumi.IntOutput)
}

// Parent stream ID
func (o DBaaSLogsOutputGraylogStreamOutput) ParentStreamId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringPtrOutput { return v.ParentStreamId }).(pulumi.StringPtrOutput)
}

// If set, pause indexing when maximum size is reach
func (o DBaaSLogsOutputGraylogStreamOutput) PauseIndexingOnMaxSize() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.PauseIndexingOnMaxSize }).(pulumi.BoolOutput)
}

// Retention ID
func (o DBaaSLogsOutputGraylogStreamOutput) RetentionId() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.RetentionId }).(pulumi.StringOutput)
}

// The service name
func (o DBaaSLogsOutputGraylogStreamOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.ServiceName }).(pulumi.StringOutput)
}

// Stream ID
func (o DBaaSLogsOutputGraylogStreamOutput) StreamId() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.StreamId }).(pulumi.StringOutput)
}

// Stream description
func (o DBaaSLogsOutputGraylogStreamOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

// Stream last update
func (o DBaaSLogsOutputGraylogStreamOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// Enable Websocket
func (o DBaaSLogsOutputGraylogStreamOutput) WebSocketEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *DBaaSLogsOutputGraylogStream) pulumi.BoolOutput { return v.WebSocketEnabled }).(pulumi.BoolOutput)
}

type DBaaSLogsOutputGraylogStreamArrayOutput struct{ *pulumi.OutputState }

func (DBaaSLogsOutputGraylogStreamArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (o DBaaSLogsOutputGraylogStreamArrayOutput) ToDBaaSLogsOutputGraylogStreamArrayOutput() DBaaSLogsOutputGraylogStreamArrayOutput {
	return o
}

func (o DBaaSLogsOutputGraylogStreamArrayOutput) ToDBaaSLogsOutputGraylogStreamArrayOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamArrayOutput {
	return o
}

func (o DBaaSLogsOutputGraylogStreamArrayOutput) Index(i pulumi.IntInput) DBaaSLogsOutputGraylogStreamOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DBaaSLogsOutputGraylogStream {
		return vs[0].([]*DBaaSLogsOutputGraylogStream)[vs[1].(int)]
	}).(DBaaSLogsOutputGraylogStreamOutput)
}

type DBaaSLogsOutputGraylogStreamMapOutput struct{ *pulumi.OutputState }

func (DBaaSLogsOutputGraylogStreamMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DBaaSLogsOutputGraylogStream)(nil)).Elem()
}

func (o DBaaSLogsOutputGraylogStreamMapOutput) ToDBaaSLogsOutputGraylogStreamMapOutput() DBaaSLogsOutputGraylogStreamMapOutput {
	return o
}

func (o DBaaSLogsOutputGraylogStreamMapOutput) ToDBaaSLogsOutputGraylogStreamMapOutputWithContext(ctx context.Context) DBaaSLogsOutputGraylogStreamMapOutput {
	return o
}

func (o DBaaSLogsOutputGraylogStreamMapOutput) MapIndex(k pulumi.StringInput) DBaaSLogsOutputGraylogStreamOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DBaaSLogsOutputGraylogStream {
		return vs[0].(map[string]*DBaaSLogsOutputGraylogStream)[vs[1].(string)]
	}).(DBaaSLogsOutputGraylogStreamOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DBaaSLogsOutputGraylogStreamInput)(nil)).Elem(), &DBaaSLogsOutputGraylogStream{})
	pulumi.RegisterInputType(reflect.TypeOf((*DBaaSLogsOutputGraylogStreamArrayInput)(nil)).Elem(), DBaaSLogsOutputGraylogStreamArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DBaaSLogsOutputGraylogStreamMapInput)(nil)).Elem(), DBaaSLogsOutputGraylogStreamMap{})
	pulumi.RegisterOutputType(DBaaSLogsOutputGraylogStreamOutput{})
	pulumi.RegisterOutputType(DBaaSLogsOutputGraylogStreamArrayOutput{})
	pulumi.RegisterOutputType(DBaaSLogsOutputGraylogStreamMapOutput{})
}
