// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a DBaas logs input engine.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ovh/sdk/go/ovh"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := ovh.GetDBaaSLogsInputEngine(ctx, &GetDBaaSLogsInputEngineArgs{
// 			IsDeprecated: pulumi.BoolRef(true),
// 			Name:         pulumi.StringRef("logstash"),
// 			Version:      pulumi.StringRef("6.8"),
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetDBaaSLogsInputEngine(ctx *pulumi.Context, args *GetDBaaSLogsInputEngineArgs, opts ...pulumi.InvokeOption) (*GetDBaaSLogsInputEngineResult, error) {
	var rv GetDBaaSLogsInputEngineResult
	err := ctx.Invoke("ovh:index/getDBaaSLogsInputEngine:getDBaaSLogsInputEngine", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDBaaSLogsInputEngine.
type GetDBaaSLogsInputEngineArgs struct {
	// Indicates if engine will soon not be supported.
	IsDeprecated *bool `pulumi:"isDeprecated"`
	// The name of the logs input engine.
	Name *string `pulumi:"name"`
	// Software version
	Version *string `pulumi:"version"`
}

// A collection of values returned by getDBaaSLogsInputEngine.
type GetDBaaSLogsInputEngineResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	IsDeprecated bool   `pulumi:"isDeprecated"`
	Name         string `pulumi:"name"`
	Version      string `pulumi:"version"`
}

func GetDBaaSLogsInputEngineOutput(ctx *pulumi.Context, args GetDBaaSLogsInputEngineOutputArgs, opts ...pulumi.InvokeOption) GetDBaaSLogsInputEngineResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDBaaSLogsInputEngineResult, error) {
			args := v.(GetDBaaSLogsInputEngineArgs)
			r, err := GetDBaaSLogsInputEngine(ctx, &args, opts...)
			var s GetDBaaSLogsInputEngineResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDBaaSLogsInputEngineResultOutput)
}

// A collection of arguments for invoking getDBaaSLogsInputEngine.
type GetDBaaSLogsInputEngineOutputArgs struct {
	// Indicates if engine will soon not be supported.
	IsDeprecated pulumi.BoolPtrInput `pulumi:"isDeprecated"`
	// The name of the logs input engine.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Software version
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (GetDBaaSLogsInputEngineOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDBaaSLogsInputEngineArgs)(nil)).Elem()
}

// A collection of values returned by getDBaaSLogsInputEngine.
type GetDBaaSLogsInputEngineResultOutput struct{ *pulumi.OutputState }

func (GetDBaaSLogsInputEngineResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDBaaSLogsInputEngineResult)(nil)).Elem()
}

func (o GetDBaaSLogsInputEngineResultOutput) ToGetDBaaSLogsInputEngineResultOutput() GetDBaaSLogsInputEngineResultOutput {
	return o
}

func (o GetDBaaSLogsInputEngineResultOutput) ToGetDBaaSLogsInputEngineResultOutputWithContext(ctx context.Context) GetDBaaSLogsInputEngineResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetDBaaSLogsInputEngineResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDBaaSLogsInputEngineResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDBaaSLogsInputEngineResultOutput) IsDeprecated() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDBaaSLogsInputEngineResult) bool { return v.IsDeprecated }).(pulumi.BoolOutput)
}

func (o GetDBaaSLogsInputEngineResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDBaaSLogsInputEngineResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDBaaSLogsInputEngineResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetDBaaSLogsInputEngineResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDBaaSLogsInputEngineResultOutput{})
}
