// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about a DBaas logs input engine.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const logstash = pulumi.output(ovh.getDBaaSLogsInputEngine({
 *     isDeprecated: true,
 *     name: "logstash",
 *     version: "6.8",
 * }));
 * ```
 */
export function getDBaaSLogsInputEngine(args?: GetDBaaSLogsInputEngineArgs, opts?: pulumi.InvokeOptions): Promise<GetDBaaSLogsInputEngineResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getDBaaSLogsInputEngine:getDBaaSLogsInputEngine", {
        "isDeprecated": args.isDeprecated,
        "name": args.name,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getDBaaSLogsInputEngine.
 */
export interface GetDBaaSLogsInputEngineArgs {
    /**
     * Indicates if engine will soon not be supported.
     */
    isDeprecated?: boolean;
    /**
     * The name of the logs input engine.
     */
    name?: string;
    /**
     * Software version
     */
    version?: string;
}

/**
 * A collection of values returned by getDBaaSLogsInputEngine.
 */
export interface GetDBaaSLogsInputEngineResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly isDeprecated: boolean;
    readonly name: string;
    readonly version: string;
}

export function getDBaaSLogsInputEngineOutput(args?: GetDBaaSLogsInputEngineOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDBaaSLogsInputEngineResult> {
    return pulumi.output(args).apply(a => getDBaaSLogsInputEngine(a, opts))
}

/**
 * A collection of arguments for invoking getDBaaSLogsInputEngine.
 */
export interface GetDBaaSLogsInputEngineOutputArgs {
    /**
     * Indicates if engine will soon not be supported.
     */
    isDeprecated?: pulumi.Input<boolean>;
    /**
     * The name of the logs input engine.
     */
    name?: pulumi.Input<string>;
    /**
     * Software version
     */
    version?: pulumi.Input<string>;
}
